sudo: required

language: generic

services:
  - docker

before_install: 
  - echo "start Creating an image with dockerfile"
  - docker build -t franc/docker_react_app -f dockerfile.dev .

script:
  - docker run -e CI=true franc/docker_react_app npm run test -- --coverage

after_success:
  - echo "Test Success!!"